language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - doxygen
      - python
script:
  - make all CC=$CC && make install CC=$CC PREFIX=devimage
deploy:
  on:
    repo: guillon/mdi
    condition: $CC = gcc
  provider: launchpad
  slug: "~christophe-guillon/mdi/trunk"
  oauth_token: $LAUNCHPAD_TOKEN
  oauth_token_secret: $LAUNCHPAD_TOKEN_SECRET
env:
  global:
  - secure: JHxcNnz+ORa2lwpFUEM+D5k1o7N+h5eaW7WPaU3U1h2XEyjGi9fgfrG3xo+5EV/hbsmEsDO5Ne0f9yyGkDSwd3uuLjv03MNSX527qz881+HAAGUz+3FOZtl6EqvG/WBJB+E5p/RMI+gRTgcUVBVKq6MjneYmrFW4nOut2HsVMQH2Uk+R8hLcFHaW7oyE05CdqpDU828bkcgrn16CfJiZ2Tada5beM87FHk3gtijqPLDDD8BpgPx4P1fVmvFd04LRgcyVET0fev0zqfs2IeNW6a96jlWJ6KjF253Wb6ajwwrWPInwII3M+ZaWuDxmqRBCTvHzkW5RK4XyO9CsN0TRsNPUVo+93npCvg/nYQlXl/uQmTgxdFLK9qErqDfIQjfOqtGojJamWu0oVQn8ex3dqL4D7gwQE8WtDI1rn0j3XLXvs8iJ4DsIMG9xcoyuiZLO6ch9i2ZvaJZ3utfcSTp4aF5rA9tPvC4qo6O+tTpvm/rnXJ0OLV/QenKjCOvPWfjpSh85Mz0KUiWObKDPqM1Kz+VTYUHjFayt/lf7gZ9URD1SfdJZ/y68aoJiNJTXZfy5LmYBm3YGxGlxPpLkz6ABMPaszlo/jwxbH9CBXGcxGxxP33Z5POxFIWn8pHyv0NUDbTw2sjmM3n4+59jBLW575Y2DvJxiEryUEUPdBNJ6SMs=
  - secure: UtwWa/gQxyemKT1ioLOSxvVl6WAIVbA/YmFx5Xbk+fF55cyiDrCkhPuvq9jDLZdIzeo5kcHAoLIzMvJ+UrVrYU6mMqYin5u/G+kJbVMPZ+12cYx83BKaLmN9Q+ZE0WEePzV6Uk807Ub9pKYjPTUF4BV1KFdpuePg242MptOmfWmEqInwM+hq8WeMlHRaWYkhaldZye/D7g6SMLTEXPf2LzcYm4ide+wJlg7BzfaA8/r3SeaKO/NPBjFnCBOEQH/oUHuhd9yHx5msa3JkbRIZKqCjG6UDiFXtTrMm0Fob061hRPkXhTVH8nsmkecp+72eY4JbFCnfQeLkbo3NVvohc8OPVWKD+a9wUpmtNuA9vWjJVXFn2/HOBVffzYrSJZ+gLco5k5AT0o487m/yKzYj3fZhg+DyfqltQ+GSfpuMgsX8APvhtP8dPcobBa12AZ6bkVu+ZrpaaE/N+48DpoPWWXK8PY3KFd2fHPHiNOeS7iRVwNtOY8vqcsSbD2t2DTyUQySJH/nuHQ2LtWhQxI/1pls7+ePP1k1kCOf/3Ow/Vy5FMK4wKiTyN6RhAaYY+JP0jFj9FffxrXmkMUiMayT37OyWePY/mwIjIdCH4chUCcFsX48kBZyJZModU7/9fP3kPvCcgQw1pHRGHfCi3mrgNKyBN3IaOWLiNy3hx1yM21o=
