language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - doxygen
      - python
script:
  - make all CC=$CC && make install CC=$CC PREFIX=devimage
deploy:
  on:
    repo: guillon/mdi
    condition: $CC = gcc
  provider: launchpad
  slug: "~christophe-guillon/mdi/trunk"
  oauth_token:
    secure: ANvSgQTojtW38VAXcwhuFjEH/PIkk9OVaJy540QZiPEucxBSoY6Rf7BYSPG7T+KZIwjp5v8hhvE79ZVbdzQMg4XUYS1d3AlvffIIlPlwUCEu+Yym4s3FEWBxENZDIhaZFKFJ7Lg4pWun5iO797YYvLjcLwTrRDC+vukeMNMZv+P64mxQOyhglqVX1x40uZeLuXkcRc9mYZ3VeELJyjdvhKPVVqvDPtrhUCpTZLvqDUmAzZSS7hs0Dm4efkWZSKGD5HO+EK0LEqp8sXvvfGo84KIfPvgmnh7y/hSW85UII6yBWxt63NOjFSOOjCNyvDQWgEK0OJhX7e4UYSelMnXAlOLhwv8OU1vazAFkN51fviZiN2y55pRxlLTV4e+zssXFNiaKWsAWDZtxAEHiRBAVbpuJ07gU2z8o0UEmHwltyQBCONI5aUTpyrjAA8spGc31ya9pWhpcv9fBpehyHMk+MfsgN3S+u6fP+hIUTNd9mQqAiVESTa0cqs0nBho6qprwVX1HBcMSQ0pAhrtfNzvyGf0FSjq3VUJKX+R3y2KHYGPKJ7mvXbMf4zfGprlE7W4sKtSdIeHRlxiM4ppxfex9WZ54J6P9Cv4XkH0659mt/KXZ8yZ9jv96cWP25Dj/Mcx927GX/HN7o1KbuV1t2PpDaq9d8VQ9E32Vdkzg/FQjBmQ=
  oauth_token_secret:
    secure: EnhmtyFUtbavqNnWnz2U0Cf3V9aJg5VrhGVAwYbUG1jAZs4Ff87y0Hp4qr7VpP67YeDcS+F8ibVOXdK4vA+1EY1aVmzYWWKlqtYjAlkRaqXXx6LwqQbJAd1okKUlkZLuHQVTtWXUtcgmzl1qZbBhRHFf7C/Ep3/qpypPR3D7WYpr7S1jAJ5UC9zohdb4K5HH127THllZPIcTfk0ZlWWAuuY7hKAOzTh7rhqU2DXI9G6HJTIiGhlgpOfHfpx6ejWPQ312ONJwO1zsR9oiL7aMevlhdxOveRPM3WdwqlrvhRMmRUM6ZdUZYAXb9Wivuzf3aq9DxEi/SoOIJXhsGFL0uN6kAptBda5vusn/YcZYIWLUxlPx/BCZNsIXzyXDlfUalDjP+6xAppvc2z94irApX+oQvBQMogXwOnl6yvwuHC/7iynYGIyNyepnWapq2OKjRHkIaMNTEDAPL3KIB5+Su3ai/5j4hkpW4rGytJZzyor9TGjJz6xOHBUgOJq23GIqe/N8fWw858EZMyBqm4Upkn629k+KQNa6rRBv/hj23fT45pL1BVxTfLudYzkujQY3P0boDBZVP0cnFcJcDZpYbJIr6ZdLFJ2RNmUlvjWWZkJ1pY/C++DVfqa1+/RaFhgFR+zyZsdibks65vxoZAP77aiALXakWBofO5fSpPt0QQE=
